openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Water
    description: Operations about water.
  - name: Users
    description: Auth operations.
servers:
  - url: http://localhost:8080
paths:
  /users/register:
    post:
      $ref: ../swagger/paths/users/register/post.yaml
  /users/login:
    post:
      $ref: ../swagger/paths/users/login/post.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/users/logout/post.yaml
  /users/refresh:
    post:
      $ref: ../swagger/paths/users/refresh/post.yaml
  /users/data:
    get:
      $ref: ../swagger/paths/users/get.yaml
  /users/updateData:
    patch:
      $ref: ../swagger/paths/users/updateData/patch.yaml
  /users/updateAvatar:
    patch:
      $ref: ../swagger/paths/users/updateAvatar/patch.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
