openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of AquaTrack app
tags:
  - name: Water
    description: Operations about water.
  - name: Users
    description: Auth operations.
servers:
  - url: https://final-project-backend-1-tzfm.onrender.com/
  - url: http://localhost:8080
  
paths:
  /users/register:
    post:
      $ref: ../swagger/paths/users/register/post.yaml
  /users/login:
    post:
      $ref: ../swagger/paths/users/login/post.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/users/logout/post.yaml
  /users/refresh:
    post:
      $ref: ../swagger/paths/users/refresh/post.yaml
  /users/data:
    get:
      $ref: ../swagger/paths/users/get.yaml
  /users/userId:
    patch:
      $ref: ../swagger/paths/users/userId/patch.yaml
  /users/avatar:
    patch:
      $ref: ../swagger/paths/users/avatar/patch.yaml
      
  /water/day:
    post:
      $ref: ../swagger/paths/water/getDay.yaml
  /water/month:
    post:
      $ref: ../swagger/paths/water/getMonth.yaml
  /water:    
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/waterId/edit.yaml
    delete:
      $ref: ../swagger/paths/water/waterId/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
